#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     spinner,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     fl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     fr,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     br,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     drawer,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int fortime = 680;
int delay = 0;
void brake(){
	motor(fl) = 0;
	motor(fr) = 0;
	motor(bl) = 0;
	motor(br) = 0;
}

void goForward(int time){
	motor(fl) = 50;
	motor(fr) = 50;
	motor(bl) = 50;
	motor(br) = 50;
	wait1Msec(time);
	brake();
}

void goBackward(int time){
	motor(fl) = -50;
	motor(fr) = -50;
	motor(bl) = -50;
	motor(br) = -50;
	wait1Msec(time);
	brake();
}

void goLeft(int time){
	motor(fl) = -50;
	motor(fr) = 50;
	motor(bl) = 50;
	motor(br) = -50;
	wait1Msec(time);
	brake();
}

void goRight(int time){
	motor(fl) = 50;
	motor(fr) = -50;
	motor(bl) = -50;
	motor(br) = 50;
	wait1Msec(time);
	brake();
}

void spinLeft(int time){
	motor(fl) = -75;
	motor(fr) = -75;
	motor(bl) = 75;
	motor(br) = 75;
	wait1Msec(time);
	brake();
}

void spinRight(int time){
	motor(fl) = 75;
	motor(fr) = 75;
	motor(bl) = -75;
	motor(br) = -75;
	wait1Msec(time);
	brake();
}

void liftUp(int time){
	motor(lift) = 100;
	wait1Msec(time);
	motor(lift) = 0;
}

void liftDown(int time){
	motor(lift) = -100;
	wait1Msec(time);
	motor(lift) = 0;
}

void servoUp (){
servo(servo1) = 180;
servo(servo2) = 180;
}

void servoDown (){
	servo(servo1) = 0;
servo(servo2) = 0;
}

void drawerUp(int time){
	motor(drawer) = 100;
	wait1Msec(time);
	motor(drawer) = 0;
}

void drawerDown(int time){
	motor(drawer) = -100;
	wait1Msec(time);
	motor(drawer) = 0;
}

void initializeRobot()
{
	bFloatDuringInactiveMotorPWM = false;
	nNxtExitClicks = 2;
	int button = 0;
	while(button != 3){
		button = nNxtButtonPressed;
		if(button == 1){
			nxtDisplayCenteredBigTextLine(3, "SHORT");
			fortime = 640;
		}
		if(button == 2){
			nxtDisplayCenteredBigTextLine(3, "LONG");
			fortime = 700;
		}
		if(button == 0){
			nxtDisplayCenteredBigTextLine(3, "NORMAL");
			fortime = 680;
		}
	}
	nxtDisplayCenteredBigTextLine(3, "DELAY?");
	wait1Msec(500);
	button = 0;
	while(button != 3){
		button = nNxtButtonPressed;
		if(button == 1){
			nxtDisplayCenteredBigTextLine(3, "10 SEC");
			delay = 10000;
		}
		if(button == 2){
			nxtDisplayCenteredBigTextLine(3, "5 SEC");
			delay = 5000;
		}
		if(button == 0){
			nxtDisplayCenteredBigTextLine(3, "0 SEC");
			delay = 0;
		}
	}
}

task main()
{
  initializeRobot();
  //waitForStart();
  wait1Msec(delay);
  goForward(2000);
  spinLeft(500);
  goForward(3000);
  servoUp();
  liftUp(3000);
  drawerUp(4000);
  spinLeft(1000);
  goForward(3000);
  goLeft(2000);
  goForward(1000);
  servoDown();
  goBackward(1000);
  goLeft(3000);
  goForward(4000);
  while (true){}
}
