#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     irseek,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S3_C1_1,     fr,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     fl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     bl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     liftA,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     liftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    cubeLiftServoA,       tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    cubeLiftServoB,       tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "HolonomicAutonomousDrives.c"

int highAValue;
int highBValue;

void initializeRobot()
{
	return;
}
task main()
{
	int highAValue, highBValue;
	initializeRobot();

	//waitForStart(); // Wait for the beginning of autonomous phase.
	for(int i = 0; i < 3; i++){
		motor[sweeper] = -76;
		wait1Msec(380);
		motor[sweeper] = 0;
	}

	servo[cubeLiftServoA] = ServoValue[cubeLiftServoA];
	servo[cubeLiftServoB] = ServoValue[cubeLiftServoB];

	wait1Msec(500);

	servo[cubeLiftServoA] = ServoValue[cubeLiftServoA] - 36;
	servo[cubeLiftServoB] = ServoValue[cubeLiftServoB] + 36;

	highAValue = ServoValue[cubeLiftServoA];
	highBValue = ServoValue[cubeLiftServoB];

	wait1Msec(500);

	motor[fl] = -100;
	motor[fr] = -100;
	motor[bl] = -100;
	motor[br] = 100;

	wait1Msec(400);

	motor[fl] = 0;
	motor[fr] = 0;
	motor[bl] = 0;
	motor[br] = 0;

	motor[fl] = 100;
	motor[bl] = 100;
	motor[fr] = -100;
	motor[br] = 25;

	wait1Msec(500);

	motor[fl] = 0;
	motor[bl] = 0;
	motor[fr] = 0;
	motor[br] = 0;

	motor[fl] = 100;
	motor[fr] = 100;
	motor[bl] = 100;
	motor[br] = -100;

	wait1Msec(700);

	motor[fl] = 0;
	motor[fr] = 0;
	motor[bl] = 0;
	motor[br] = 0;

	while(SensorValue[irseek] != 5){
		motor[fr] = -100;
		motor[fl] = -75;
		motor[br] = -60;
		motor[bl] = 75;
	}

	wait1Msec(500);

	motor[fr] = 0;
	motor[fl] = 0;
	motor[br] = 0;
	motor[bl] = 0;

	motor[liftA] = 100;
	motor[liftB] = 100;
	wait1Msec(2800);
	motor[liftA] = 0;
	motor[liftB] = 0;


	motor[fl] = 100;
	motor[fr] = 100;
	motor[bl] = 100;
	motor[br] = -100;

	wait1Msec(1100);

	motor[fl] = 0;
	motor[fr] = 0;
	motor[bl] = 0;
	motor[br] = 0;

	servo[cubeLiftServoA] = ServoValue[cubeLiftServoA] + 86;
	servo[cubeLiftServoB] = ServoValue[cubeLiftServoB] - 86;

	wait1Msec(1000);

}
