#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  return;
}


task main()
{
  initializeRobot();

  waitForStart();

  while (true)
  {
  getJoystickSettings(Joystick);

  motor[left] = (Joystick.joy1_y1 /128.0* 100;
  motor[right] = (Joystick.joy1_y2 /128.0 * 100;





  }
}
