#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S2_C1_1,     fl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     fr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C3_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C4_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C4_2,     drawer,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    lift1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    lift2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "ButtonsDefs.h"
int maxpow = 100.0;
void initializeRobot()
{

	return;
}

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	float x;
	float y;

	while (true)
	{
		getJoystickSettings(joystick);

		x = ((joystick.joy1_x1/128.0)*maxpow);
		y = ((joystick.joy1_y1/128.0)*maxpow);

		if(x > 10 || x < -10 || y > 10 || y < -10){
			motor[fl] = x+y;
			motor[fr] = y-x;
			motor[bl] = y-x;
			motor[br] = x+y;
		}
		else if(joystick.joy1_Buttons == button_right_trigger){
			motor[fr] = 100;
			motor[fl] = -100;
			motor[br] = 100;
			motor[bl] = -100;
		}
		else if(joystick.joy1_Buttons == button_left_trigger){
			motor[fr] = -100;
			motor[fl] = 100;
			motor[br] = -100;
			motor[bl] = 100;
		}
		else{
			motor[fr] = 0;
			motor[fl] = 0;
			motor[br] = 0;
			motor[bl] = 0;
		}

		if(joystick.joy1_TopHat == pov_north){
			servo[lift1] = ServoValue[lift1] -1;
			servo[lift2] = ServoValue[lift2] +1;
		}
		if(joystick.joy1_TopHat == pov_south){
			servo[lift1] = ServoValue[lift1] +1;
			servo[lift2] = ServoValue[lift2] -1;
		}

		if(joystick.joy1_Buttons == button_left_button){
			maxpow = 25.0;
		}
		if(joystick.joy1_Buttons == button_right_button){
			maxpow = 100.0;
		}
		if(joystick.joy2_Buttons == button_left_button){

			motor[lift] = -100;
		}
		else if(joystick.joy2_Buttons == button_right_button){

			motor[lift] = 100;
		}
		else{
			motor[lift] = 0;
		}

		if(joystick.joy2_Buttons == button_b){
			motor[sweeper] = -100;
		}
		else if(joystick.joy2_Buttons == button_x){
			motor[sweeper] = 100;
		}
		else{
			motor[sweeper] = 0;
		}

		if(joystick.joy2_TopHat == pov_north){
			motor[drawer] = 100;
		}
		else if(joystick.joy2_TopHat == pov_south){
			motor[drawer] = -100;
		}
		else{
			motor[drawer] = 0;
		}

		if(joystick.joy2_Buttons == button_y){
			motor[spinner] = 100;

		}
		else if(joystick.joy2_Buttons == button_a){
			motor[spinner] = -100;
		}
		else{
			motor[spinner] = 0;
		}

	}
}
